### ISSUE TITLE
Permission problem when run from `sudo su`

### ISSUE THREAD

**Issue by eddiemonge** [sindresorhus/downgrade-root#3] opened 2015-01-08 21:30 UTC
https://gist.github.com/eddiemonge/c1b8211f596ba2cdd4e3

**Comment by silverwind** [comment] 2015-01-08 21:50
I doubt this is caused by this module, and the stack trace points to the `insight` module. Can you post some code and its module dependencies, if you still think this is related to this module?

**Comment by eddiemonge** [comment] 2015-01-08 22:25
i guess the issue is that there isn't an error being thrown when it tries to downgrade. or who is it being downgraded to?

**Comment by silverwind** [comment] 2015-01-08 23:00
> who is it being downgraded to

When using sudo, it downgrades to the user who invoked sudo:

```
$ sudo node -e "require('downgrade-root')(); console.log(process.getuid())"
1000
```

When run as root, it currently downgrades to the first user-space UID, which is platform dependent, 1000 on most linux distros, 501 on OS X.

@sindresorhus regarding throwing: I see the README example wraps with a `try` but we don't actually throw?

**Comment by sindresorhus** [comment] 2015-01-09 02:52
> @sindresorhus regarding throwing: I see the README example wraps with a try but we don't actually throw?

`process.setuid` will throw if it fail downgrading the permissions.

Which is why I wrap it in try/catch here as we don't care about it failing: https://github.com/sindresorhus/root-check/blob/2e97094533d31fc101ceca71207a83865f21117d/index.js#L6-L8

**Comment by silverwind** [comment] 2015-01-09 03:39
Alright. I'll close this issue as invalid until further evidence is provided that it actually concerns this module.

**Closed as completed by silverwind** 2015-01-09 03:39 UTC
